---
services:
  nginx:
    container_name: students-nginx_configs
    image: nginx:stable-alpine-perl
    networks:
      - students-app-network
    volumes:
      - ./default.conf:/etc/nginx_configs/conf.d/default.conf
    ports:
      - "80:80"

  app:
    container_name: students-app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - students-app-network
    volumes:
      - students-data:/app/src/data

volumes:
  students-data:

networks:
  students-app-network: